/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controllers.Validator;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo
 */
public class AccountView extends javax.swing.JFrame {

    private final Validator validator;
    private final Cashier cashier;

    /**
     * Creates new form AccountView
     *
     * @param cashier
     */
    public AccountView(Cashier cashier) {
        validator = new Validator();
        this.cashier = cashier;
        initComponents();
    }

    private AccountView() {
        validator = new Validator();
        cashier = new Cashier();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        idClient = new javax.swing.JTextField();
        crearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        savings = new javax.swing.JRadioButton();
        currents = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cp = new javax.swing.JRadioButton();
        np = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        errorAccountID = new javax.swing.JLabel();
        errorClientID = new javax.swing.JLabel();
        errorAccountType = new javax.swing.JLabel();
        errorClientType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(307, 268));
        setMinimumSize(new java.awt.Dimension(307, 268));
        setResizable(false);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });

        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("ID de la cuenta:");

        jLabel2.setText("Identificacíon del cliente:");

        savings.setText("Cuenta de ahorros");
        savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsActionPerformed(evt);
            }
        });

        currents.setText("Cuenta corriente");
        currents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentsActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de cuenta:");

        cp.setText("Empresa");
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });

        np.setText("Persona natural");
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de cliente:");

        errorAccountID.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        errorAccountID.setForeground(new java.awt.Color(254, 254, 254));
        errorAccountID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorAccountID.setText(".");

        errorClientID.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        errorClientID.setForeground(new java.awt.Color(254, 254, 254));
        errorClientID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorClientID.setText(".");

        errorAccountType.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        errorAccountType.setForeground(new java.awt.Color(254, 254, 254));
        errorAccountType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorAccountType.setText(".");

        errorClientType.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        errorClientType.setForeground(new java.awt.Color(254, 254, 254));
        errorClientType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorClientType.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorAccountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorClientID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currents)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(savings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(errorAccountID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(idClient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cp)
                                    .addComponent(np))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(errorClientType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addComponent(errorAccountID)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savings)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currents)
                .addGap(0, 0, 0)
                .addComponent(errorAccountType)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idClient, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0)
                .addComponent(errorClientID)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(np)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addComponent(cp)
                .addGap(0, 0, 0)
                .addComponent(errorClientType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed

        int error = validator.validateInputAccountView(id.getText(), savings.isSelected(), currents.isSelected(),
                idClient.getText(), np.isSelected(), cp.isSelected(), errorAccountID, errorAccountType, errorClientID,
                errorClientType);
        if (error != 0) {
            return;
        }
        if (!validator.isDuplicateClient(idClient.getText(), savings.isSelected())) {
            getClientView();
        } else {
            cashier.addAccount(id.getText(), idClient.getText(), savings.isSelected());
            Message.getMessageSuccefullAccount();
            this.dispose();
            cashier.setVisible(true);
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    private void savingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsActionPerformed
        if (savings.isSelected()) {
            currents.setSelected(false);
            savings.setEnabled(false);
            currents.setEnabled(true);
        }
    }//GEN-LAST:event_savingsActionPerformed

    private void currentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentsActionPerformed
        if (currents.isSelected()) {
            savings.setSelected(false);
            currents.setEnabled(false);
            savings.setEnabled(true);
        }
    }//GEN-LAST:event_currentsActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        if (cp.isSelected()) {
            np.setSelected(false);
            cp.setEnabled(false);
            np.setEnabled(true);
        }
    }//GEN-LAST:event_cpActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        if (np.isSelected()) {
            cp.setSelected(false);
            np.setEnabled(false);
            cp.setEnabled(true);
        }
    }//GEN-LAST:event_npActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed

    }//GEN-LAST:event_idKeyPressed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased

    }//GEN-LAST:event_idKeyReleased

    public void getClientView() {
        if (JOptionPane.showConfirmDialog(null, "La identificacion de cliente " + idClient.getText() + " no se encuentra registrada ¿Desea registarlo?", "Identificacion no registrada",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            ClientView abrir = new ClientView(cashier, this);
            abrir.setVisible(true);
            this.setVisible(false);
            if (np.isSelected()) {
                abrir.personActivate(idClient.getText());
            } else {
                abrir.companyActivate(idClient.getText());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cp;
    private javax.swing.JButton crearButton;
    private javax.swing.JRadioButton currents;
    private javax.swing.JLabel errorAccountID;
    private javax.swing.JLabel errorAccountType;
    private javax.swing.JLabel errorClientID;
    private javax.swing.JLabel errorClientType;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton np;
    private javax.swing.JRadioButton savings;
    // End of variables declaration//GEN-END:variables
}
